[package]
name = "hsl10n"
version = "3.0.0"
authors = ["Woomy4680-exe <matzar1808@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
structopt = "0.3"